### ISSUE TITLE
Client fails to run due to missing april library

### ISSUE THREAD

**Issue by RedEtherbloom** [lavafroth/tempest#6]
Hi,
I'm currently trying to get the NixOS dev shell running on NixOS unstable.

I get the following error "./target/release/tempest-client: error while loading shared libraries: libaprilasr.so.2023: cannot open shared object file: No such file or directory".

I could not find a mention of aprl-asr in the flake.nix, is it missing?

(Will try to add a fetchGit locally. Very new to using flakes.)

**Comment by lavafroth** [comment]
Hello there!
Since you're using cargo build, you'll have to manually set LD_LIBRARY_PATH to include the compiled libaprilasr shared object file. The quick and dirty way is to use cargo run instead of cargo build.

Thank you for your interest in tempest.

**Comment by lavafroth** [comment]
Hello there!
Since you're using cargo build, you'll have to manually set LD_LIBRARY_PATH to include the compiled libaprilasr shared object file. The quick and dirty way is to use cargo run instead of cargo build.

Thus, you'd replace
 
```
./target/release/tempest-client
```

with

```
cargo run --bin tempest-client -- some_token
```

This is mainly due to CFFI with the libaprilasr library that I stole from Josh Habdas. I'll eventually port it to pure Rust. There's a repo called [bowlby](https://github.com/lavafroth/bowlby) to do just that. For now it's stuck in a limbo since I'm caught up with other things. 

Thank you for your interest in tempest.
